name: Scala CI

on:
  pull_requests:
  branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribuiton: 'adopt'
    - name: Run tests
      run: sbt test